project:
  type: website

website:
  title: "Nina Livre"
  navbar:
    right:
      - about.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    lang: pt

editor: visual

